### ISSUE TITLE
Misbehaving SSL clients can force server exit

### ISSUE THREAD

**Issue by wjjensen** [mozy/mordor#14]
I found this when using a client based on curl, with a mordor server.  If I returned an HTTP response with connection: close set, and also closed the SSLStream by using HTTP::respondError() with closeConnection set to true, then invariably the server would die from a MORDOR_NOTREACHED assertion.  If I only set the Connection header and allowed the client to initiate the SSL teartdown then all was well.

I imagine this is a race for initiating the orderly SSL teardown, where one side or the other is missing a "close notify."  But it occurs to me that it may be common to find SSL clients that don't implement orderly SSL shutdown at all, and the server should be prepared to deal with a socket disconnect after initiating SSL_shutdown() but prior to receiving the peer's close notify.

```
    ==== old/mordor/streams/ssl.cpp (text) - new/mordor/streams/ssl.cpp (text) ==== content
    @@ -284,6 +284,12 @@
                             << "): " << result << " (" << error << ")";
                         break;
                     }
    +                               else
    +                               {
    +                                       MORDOR_LOG_WARNING(g_log) << this << " SSL_shutdown(" << m_ssl.get()
    +                                               << "): " << result << " (" << error << ") Peer disconnected without sending close_notify";
    +                                       goto SSLStream_close_final;
    +                               }
                     MORDOR_NOTREACHED();
                 case SSL_ERROR_SSL:
                     {
    @@ -300,7 +306,8 @@
             }
             break;
         }
    -    parent()->close();
    +SSLStream_close_final:
    +       parent()->close();
     }

     size_t
```

**Comment by ccutrer** [comment]
Do you have a log with mordor:streams:ssl turned up to trace enabled, as well as any special switches you use with Curl?  I'm just trying to understand the underlying cause; the only other possible value for result in that case should be "1", which means that it received and processed the close-notify from the client.  However, due to how mordor uses openssl, SSL_shutdown cannot directly read any data - it should have already received the close-notify (as checked immediately before calling SSL_shutdown), or it should give an WANT_READ error.  The only possibility I can think of is that the close-notify is already in the buffer we gave OpenSSL, but a prior SSL_read didn't process it.  I've been unable to reproduce that case in a unit test.

Finally, how are you setting the Connection header?  All that HTTP::respondError does if you set closeConnection is request->response().general.connection.insert("close"); - i.e. it should behave the same as if you set the header yourself and didn't tell respondError to set it.

**Comment by wjjensen** [comment]
This only happens with very particular client behavior, which unfortunately is the behavior of the client app I'm working with.  The client is performing a chunked upload, with 100-continue disabled.  The content must be over a certain length to reproduce. I imagine the problem is related to either curl not watching for read events on the socket until the upload completes (so it misses the close_notify and exits on a RST without sending its own close_notify), or the receive buffer on the server side is full of HTTP body prior to receipt of the close_notify and the intermediate mem BIO doesn't cycle through all that content prior to the NOT_REACHED being thrown.   But anyway, some clients will not send close_notify at all, and I figured it's poor form on the server's part to terminate when faced with a badly behaved client.

To simulate the upload conditions, use curl command line with the following form:
curl -1 -k -H "Transfer-Encoding: chunked" -H "Expect:" -T <local_file> <server_url>

I attached the requested log both unpatched (ssl.log) and patched (ssl-patched.log).  

Regarding the different behaviors on closing the client, I probably mis-remembered when I wrote that up.  To clarify:  If I close the connection from the server side by appending "connection: close", the problem reproduces; if I simply respond with an HTTP error code but continue using a keep-alive session, my client initiates the session teardown (since it requires a 200 response) and all is well.

**Comment by ccutrer** [comment]
Apparently github doesn't handle e-mail attachments in issues; you can either send them directly to me, or to mordor-users@googlegroups.com.

**Comment by ccutrer** [comment]
I was able to repro it.  Interestingly it depends on the version of OpenSSL.  The unit test I added in that commit triggered the assertion on Ubuntu Natty, but not on Mac OS X Snow Leopard.  I applied a slight variant of your patch to my fork.  If Mozy ever gets around to getting a Contributor License Agreement, they'll merge it back in here.  Until then, I recommend that you use my fork, rather than Mozy's - it has several major bug fixes reported by other community members.
