### ISSUE TITLE
Asynchronous DNS Lookups

### ISSUE THREAD

**Issue by rphillips** [mozy/mordor#2]
I believe a nice addition to mordor would be an asynchronous DNS resolver backend using C-Ares. The API may need to change slightly to support this.

Thoughts?

**Comment by ccutrer** [comment]
I've toyed with asynchronous DNS resolution before, but decided it would be too much work to write from scratch.  I was unaware of C-Ares.  I believe it could be integrated quite nicely, except for Windows.  Mordor uses native I/O Completion ports on Windows, instead of Windows' select emulation.  This means a different I/O model under the covers.  I guess I could use WSAEventSelect and still use C-Ares underneath... hopefully you're not trying to push too many DNS requests at once, since using WSAEventSelect (and Mordor::IOManager's support for Win32 events) isn't as high performance as directly using completion ports.

Thanks for the suggestion!

**Comment by rphillips** [comment]
Hi Cody,

My use case would be on Linux and other unix based system. I don't know how this would apply to Windows, but it does seem like a harder domain.

Feel free to close this bug out or keep it around as a reminder.

**Comment by ccutrer** [comment]
Definitely keeping it around.  You've got my wheels turning.  There are multiple libraries that were originally designed for a POSIX world that expect that type of asynchronous interface.  One example is libpq, which I already have a mordor wrapper for, but I just punted on the async-ness in Windows.  I could abstract out the slightly different interface in the Windows IOManager, and then it would just work for libpq, for c-ares, and whatever other libraries provides similar interfaces.

**Comment by abique** [comment]
You should not try c-ares as it's buggy. I recommend you to try adns first.
Or even better, write your own!

**Comment by ArtemGr** [comment]
There's also an asynchronous DNS resolver in libevent.
